#——————————————————————————————————————————————————————————
#                          语言配置
#——————————————————————————————————————————————————————————
显示文本: true
头顶显示文本:
  - "评价人数：%评价人数% 玩家评分：%玩家评分%"
  - "信誉:%积分% 信誉等级：%信誉等级%"
查询显示文本: "积分:%积分% 信誉等级：%信誉等级%"
#——————————————————————————————————————————————————————————
#                          积分配置
#——————————————————————————————————————————————————————————
#----------------------------------------------------
#                         评分设置
#----------------------------------------------------
#汽车驾校好像是12分
基础积分: 12
#玩家积分低于这个值时，会被服务器封禁
封禁积分: 0
踢出消息: "我们不欢迎老赖"
记录格式: "%时间%被%执行者%评分%积分%原因:%原因%"
时间格式: "yyyy/MM/dd/HH:mm:ss"
#----------------------------------------------------
#                         评价设置
#----------------------------------------------------
#至少有多少个玩家评分后才计算平均分
最小数量: 5
#玩家平均分低于此值会被服务器封禁,建议设置最小数量多一点防止恶意评价
最小平均分: 1.2
#——————————————————————————————————————————————————————————
#                          显示配置
#——————————————————————————————————————————————————————————
#玩家平均分保留小数位数
保留小数位数: 2
#玩家评分没有的情况下吓死的字符
无评分显示字符: "暂无"
#积分显示位置相对玩家坐标需要移动下才可以完美的显示到玩家头上
上移位置: 2.4
#信用等级名称配置
信用等级名称:
  - 最低积分: 1
    最高积分: 5
    名称: "老赖"
  - 最低积分: 6
    最高积分: 10
    名称: "中等"
  - 最低积分: 11
    最高积分: 20
    名称: "优秀"
#——————————————————————————————————————————————————————————
#                          工作配置
#——————————————————————————————————————————————————————————
跨服模式: false
工作路径: "C:/工作路径"